load("//tensorboard/defs:defs.bzl", "tf_ts_library")

package(default_visibility = ["//tensorboard/webapp/widgets/line_chart_v2/lib:__pkg__"])

tf_ts_library(
    name = "roboto",
    srcs = [
        "roboto.ts",
    ],
)
